#!/usr/bin/env python

w = open('pywdns/wdns_constants.py', 'w')

for line in open('wdns/constants.h'):
    if 'WDNS_TYPE_' in line:
        rrtype = line.split()[1].split('_', 2)[2]
        rrtype_val = line.split()[-1]
        w.write('TYPE_%s = %s\n' % (rrtype, rrtype_val))
    elif 'WDNS_CLASS_' in line:
        rrclass = line.split()[1].split('_', 2)[2]
        rrclass_val = line.split()[-1]
        w.write('CLASS_%s = %s\n' % (rrclass, rrclass_val))
    elif 'WDNS_MSG_SEC_' in line:
        sec = line.split()[1].split('_', 3)[3]
        sec_val = line.split()[-1]
        w.write('SEC_%s = %s\n' % (sec, sec_val))
    elif 'WDNS_OP_' in line:
        op = line.split()[1].split('_', 2)[2]
        op_val = line.split()[-1]
        w.write('OP_%s = %s\n' % (op, op_val))
    elif 'WDNS_R_' in line:
        r = line.split()[1].split('_', 2)[2]
        r_val = line.split()[-1]
        w.write('R_%s = %s\n' % (r, r_val))

w.write('TYPES = {\n')

for line in open('wdns/constants.h'):
    if 'WDNS_TYPE_' in line:
        rrtype = line.split()[1].split('_', 2)[2]
        rrtype_val = line.split()[-1]
        w.write("'%s': %s,\n" % (rrtype, rrtype_val))

w.write('}\n')

w.close()
