language: c

compiler:
    - gcc
    - clang

before_install:
    - sudo wget -O /etc/apt/trusted.gpg.d/debian-farsightsec.gpg https://dl.farsightsecurity.com/debian/archive.pubkey
    - sudo sh -c 'echo "deb [arch=amd64] http://dl.farsightsecurity.com/debian wheezy-farsightsec main" > /etc/apt/sources.list.d/debian-farsightsec.list'
    - sudo apt-get -qq update

install:
    - sudo apt-get install -q libpcap0.8-dev libprotobuf-c0-dev protobuf-c-compiler libxs-dev zlib1g-dev docbook5-xml docbook-xsl docbook-xsl-ns xsltproc
    - sh -c 'git clone https://github.com/farsightsec/wdns.git && cd wdns && ./autogen.sh && ./configure && make && sudo make install'

script:
    - ./autogen.sh
    - ./configure
    - make
    - make distcheck
