#!/usr/bin/env python

header = '''#include "private.h"

const char *
wdns_rrclass_to_str(uint16_t rrclass)
{
	switch (rrclass) {
'''

footer = '''	}

	return (NULL);
}
'''

w = open('rrclass_to_str.c', 'w')

w.write(header)

for line in open('../constants.h'):
    if 'WDNS_CLASS_' in line:
        wdns_class = line.split()[1]
        rrclass = wdns_class.rsplit('_', 1)[1]
        w.write('\tcase %s: return ("%s");\n' % (wdns_class, rrclass))

w.write(footer)
w.close()
