#!/usr/bin/env python

header = '''#include "private.h"

const char *
wdns_rrtype_to_str(uint16_t rrtype)
{
	switch (rrtype) {
'''

footer = '''	}

	return (NULL);
}
'''

w = open('rrtype_to_str.c', 'w')

w.write(header)

for line in open('../constants.h'):
    if 'WDNS_TYPE_' in line:
        wdns_type = line.split()[1]
        rrtype = wdns_type.rsplit('_', 1)[1]
        w.write('\tcase %s: return ("%s");\n' % (wdns_type, rrtype))

w.write(footer)
w.close()
