#ifndef NMSG_ISC_DEFS_H
#define NMSG_ISC_DEFS_H

#define NMSG_VENDOR_ISC_NCAP_ID		1
#define NMSG_VENDOR_ISC_NCAP_NAME	"ncap"

#define NMSG_VENDOR_ISC_EMAIL_ID	2
#define NMSG_VENDOR_ISC_EMAIL_NAME	"email"

#define NMSG_VENDOR_ISC_LINKPAIR_ID	3
#define NMSG_VENDOR_ISC_LINKPAIR_NAME	"linkpair"

#define NMSG_VENDOR_ISC_HTTP_ID		4
#define NMSG_VENDOR_ISC_HTTP_NAME	"http"

#define NMSG_VENDOR_ISC_IPCONN_ID	5
#define NMSG_VENDOR_ISC_IPCONN_NAME	"ipconn"

#define NMSG_VENDOR_ISC_LOGLINE_ID	6
#define NMSG_VENDOR_ISC_LOGLINE_NAME	"logline"

#define NMSG_VENDOR_ISC_DNS_ID		7
#define NMSG_VENDOR_ISC_DNS_NAME	"dns"

#define NMSG_VENDOR_ISC_PKT_ID		8
#define NMSG_VENDOR_ISC_PKT_NAME	"pkt"

#define NMSG_VENDOR_ISC_DNSQR_ID	9
#define NMSG_VENDOR_ISC_DNSQR_NAME	"dnsqr"

#define NMSG_VENDOR_ISC_XML_ID		10
#define NMSG_VENDOR_ISC_XML_NAME	"xml"

#define NMSG_VENDOR_ISC_ENCODE_ID	11
#define NMSG_VENDOR_ISC_ENCODE_NAME	"encode"

#endif /* NMSG_ISC_DEFS_H */
