#ifndef WRECK_DNS_CONSTANTS_H
#define WRECK_DNS_CONSTANTS_H

#define WRECK_DNS_LEN_HEADER		12
#define WRECK_DNS_MAXLEN_NAME		255

#define WRECK_DNS_PRESLEN_TYPE_A	16
#define WRECK_DNS_PRESLEN_TYPE_AAAA	46

#define WRECK_DNS_OP_QUERY		0
#define WRECK_DNS_OP_IQUERY		1
#define WRECK_DNS_OP_STATUS		2
#define WRECK_DNS_OP_NOTIFY		4
#define WRECK_DNS_OP_UPDATE		5

#define WRECK_DNS_R_NOERROR		0
#define WRECK_DNS_R_FORMERR		1
#define WRECK_DNS_R_SERVFAIL		2
#define WRECK_DNS_R_NXDOMAIN		3
#define WRECK_DNS_R_NOTIMP		4
#define WRECK_DNS_R_REFUSED		5
#define WRECK_DNS_R_YXDOMAIN		6
#define WRECK_DNS_R_YXRRSET		7
#define WRECK_DNS_R_NXRRSET		8
#define WRECK_DNS_R_NOTAUTH		9
#define WRECK_DNS_R_NOTZONE		10
#define WRECK_DNS_R_BADVERS		16
#define WRECK_DNS_R_BADSIG		16
#define WRECK_DNS_R_BADKEY		17
#define WRECK_DNS_R_BADTIME		18
#define WRECK_DNS_R_BADMODE		19
#define WRECK_DNS_R_BADNAME		20
#define WRECK_DNS_R_BADALG		21
#define WRECK_DNS_R_BADTRUNC		22

#define WRECK_DNS_CLASS_IN		1
#define WRECK_DNS_CLASS_CH		3
#define WRECK_DNS_CLASS_HS		4
#define WRECK_DNS_CLASS_NONE		254
#define WRECK_DNS_CLASS_ANY		255

#define WRECK_DNS_TYPE_A		1
#define WRECK_DNS_TYPE_NS		2
#define WRECK_DNS_TYPE_MD		3
#define WRECK_DNS_TYPE_MF		4
#define WRECK_DNS_TYPE_CNAME		5
#define WRECK_DNS_TYPE_SOA		6
#define WRECK_DNS_TYPE_MB		7
#define WRECK_DNS_TYPE_MG		8
#define WRECK_DNS_TYPE_MR		9
#define WRECK_DNS_TYPE_NULL		10
#define WRECK_DNS_TYPE_WKS		11
#define WRECK_DNS_TYPE_PTR		12
#define WRECK_DNS_TYPE_HINFO		13
#define WRECK_DNS_TYPE_MINFO		14
#define WRECK_DNS_TYPE_MX		15
#define WRECK_DNS_TYPE_TXT		16
#define WRECK_DNS_TYPE_RP		17
#define WRECK_DNS_TYPE_AFSDB		18
#define WRECK_DNS_TYPE_X25		19
#define WRECK_DNS_TYPE_ISDN		20
#define WRECK_DNS_TYPE_RT		21
#define WRECK_DNS_TYPE_NSAP		22
#define WRECK_DNS_TYPE_NSAP_PTR		23
#define WRECK_DNS_TYPE_SIG		24
#define WRECK_DNS_TYPE_KEY		25
#define WRECK_DNS_TYPE_PX		26
#define WRECK_DNS_TYPE_GPOS		27
#define WRECK_DNS_TYPE_AAAA		28
#define WRECK_DNS_TYPE_LOC		29
#define WRECK_DNS_TYPE_NXT		30
#define WRECK_DNS_TYPE_EID		31
#define WRECK_DNS_TYPE_NIMLOC		32
#define WRECK_DNS_TYPE_SRV		33
#define WRECK_DNS_TYPE_ATMA		34
#define WRECK_DNS_TYPE_NAPTR		35
#define WRECK_DNS_TYPE_KX		36
#define WRECK_DNS_TYPE_CERT		37
#define WRECK_DNS_TYPE_A6		38
#define WRECK_DNS_TYPE_DNAME		39
#define WRECK_DNS_TYPE_SINK		40
#define WRECK_DNS_TYPE_OPT		41
#define WRECK_DNS_TYPE_APL		42
#define WRECK_DNS_TYPE_DS		43
#define WRECK_DNS_TYPE_SSHFP		44
#define WRECK_DNS_TYPE_IPSECKEY		45
#define WRECK_DNS_TYPE_RRSIG		46
#define WRECK_DNS_TYPE_NSEC		47
#define WRECK_DNS_TYPE_DNSKEY		48
#define WRECK_DNS_TYPE_DHCID		49
#define WRECK_DNS_TYPE_NSEC3		50
#define WRECK_DNS_TYPE_NSEC3PARAM	51
#define WRECK_DNS_TYPE_HIP		55
#define WRECK_DNS_TYPE_NINFO		56
#define WRECK_DNS_TYPE_RKEY		57
#define WRECK_DNS_TYPE_SPF		99
#define WRECK_DNS_TYPE_TKEY		249
#define WRECK_DNS_TYPE_TSIG		250
#define WRECK_DNS_TYPE_IXFR		251
#define WRECK_DNS_TYPE_AXFR		252
#define WRECK_DNS_TYPE_MAILB		253
#define WRECK_DNS_TYPE_MAILA		254
#define WRECK_DNS_TYPE_ANY		255
#define WRECK_DNS_TYPE_TA		32768
#define WRECK_DNS_TYPE_DLV		32769

#endif /* WRECK_DNS_CONSTANTS_H */
