/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "nmsg.pb-c.h"
void   nmsg__nmsg__init
                     (Nmsg__Nmsg         *message)
{
  static Nmsg__Nmsg init_value = NMSG__NMSG__INIT;
  *message = init_value;
}
size_t nmsg__nmsg__get_packed_size
                     (const Nmsg__Nmsg *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__nmsg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nmsg__nmsg__pack
                     (const Nmsg__Nmsg *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__nmsg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nmsg__nmsg__pack_to_buffer
                     (const Nmsg__Nmsg *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__nmsg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nmsg__Nmsg *
       nmsg__nmsg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nmsg__Nmsg *)
     protobuf_c_message_unpack (&nmsg__nmsg__descriptor,
                                allocator, len, data);
}
void   nmsg__nmsg__free_unpacked
                     (Nmsg__Nmsg *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__nmsg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nmsg__nmsg_fragment__init
                     (Nmsg__NmsgFragment         *message)
{
  static Nmsg__NmsgFragment init_value = NMSG__NMSG_FRAGMENT__INIT;
  *message = init_value;
}
size_t nmsg__nmsg_fragment__get_packed_size
                     (const Nmsg__NmsgFragment *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__nmsg_fragment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nmsg__nmsg_fragment__pack
                     (const Nmsg__NmsgFragment *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__nmsg_fragment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nmsg__nmsg_fragment__pack_to_buffer
                     (const Nmsg__NmsgFragment *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__nmsg_fragment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nmsg__NmsgFragment *
       nmsg__nmsg_fragment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nmsg__NmsgFragment *)
     protobuf_c_message_unpack (&nmsg__nmsg_fragment__descriptor,
                                allocator, len, data);
}
void   nmsg__nmsg_fragment__free_unpacked
                     (Nmsg__NmsgFragment *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__nmsg_fragment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nmsg__nmsg_payload__init
                     (Nmsg__NmsgPayload         *message)
{
  static Nmsg__NmsgPayload init_value = NMSG__NMSG_PAYLOAD__INIT;
  *message = init_value;
}
size_t nmsg__nmsg_payload__get_packed_size
                     (const Nmsg__NmsgPayload *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__nmsg_payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nmsg__nmsg_payload__pack
                     (const Nmsg__NmsgPayload *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__nmsg_payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nmsg__nmsg_payload__pack_to_buffer
                     (const Nmsg__NmsgPayload *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__nmsg_payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nmsg__NmsgPayload *
       nmsg__nmsg_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nmsg__NmsgPayload *)
     protobuf_c_message_unpack (&nmsg__nmsg_payload__descriptor,
                                allocator, len, data);
}
void   nmsg__nmsg_payload__free_unpacked
                     (Nmsg__NmsgPayload *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__nmsg_payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nmsg__nmsg__field_descriptors[1] =
{
  {
    "payloads",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Nmsg__Nmsg, n_payloads),
    PROTOBUF_C_OFFSETOF(Nmsg__Nmsg, payloads),
    &nmsg__nmsg_payload__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned nmsg__nmsg__field_indices_by_name[] = {
  0,   /* field[0] = payloads */
};
static const ProtobufCIntRange nmsg__nmsg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nmsg__nmsg__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nmsg.Nmsg",
  "Nmsg",
  "Nmsg__Nmsg",
  "nmsg",
  sizeof(Nmsg__Nmsg),
  1,
  nmsg__nmsg__field_descriptors,
  nmsg__nmsg__field_indices_by_name,
  1,  nmsg__nmsg__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor nmsg__nmsg_fragment__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__NmsgFragment, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "current",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__NmsgFragment, current),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "last",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__NmsgFragment, last),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "fragment",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__NmsgFragment, fragment),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned nmsg__nmsg_fragment__field_indices_by_name[] = {
  1,   /* field[1] = current */
  3,   /* field[3] = fragment */
  0,   /* field[0] = id */
  2,   /* field[2] = last */
};
static const ProtobufCIntRange nmsg__nmsg_fragment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor nmsg__nmsg_fragment__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nmsg.NmsgFragment",
  "NmsgFragment",
  "Nmsg__NmsgFragment",
  "nmsg",
  sizeof(Nmsg__NmsgFragment),
  4,
  nmsg__nmsg_fragment__field_descriptors,
  nmsg__nmsg_fragment__field_indices_by_name,
  1,  nmsg__nmsg_fragment__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor nmsg__nmsg_payload__field_descriptors[6] =
{
  {
    "vid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__NmsgPayload, vid),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "msgtype",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__NmsgPayload, msgtype),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "time_sec",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__NmsgPayload, time_sec),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "time_nsec",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__NmsgPayload, time_nsec),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "payload",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__NmsgPayload, has_payload),
    PROTOBUF_C_OFFSETOF(Nmsg__NmsgPayload, payload),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "user",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Nmsg__NmsgPayload, n_user),
    PROTOBUF_C_OFFSETOF(Nmsg__NmsgPayload, user),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned nmsg__nmsg_payload__field_indices_by_name[] = {
  1,   /* field[1] = msgtype */
  4,   /* field[4] = payload */
  3,   /* field[3] = time_nsec */
  2,   /* field[2] = time_sec */
  5,   /* field[5] = user */
  0,   /* field[0] = vid */
};
static const ProtobufCIntRange nmsg__nmsg_payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor nmsg__nmsg_payload__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nmsg.NmsgPayload",
  "NmsgPayload",
  "Nmsg__NmsgPayload",
  "nmsg",
  sizeof(Nmsg__NmsgPayload),
  6,
  nmsg__nmsg_payload__field_descriptors,
  nmsg__nmsg_payload__field_indices_by_name,
  1,  nmsg__nmsg_payload__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
