/*
 * Copyright (c) 2008-2011 by Internet Systems Consortium, Inc. ("ISC")
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS.  IN NO EVENT SHALL ISC BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
 * OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/*! \file nmsg/vendors.h
 * \brief NMSG vendor ID values.
 */

#ifndef NMSG_VENDORS_H
#define NMSG_VENDORS_H

#define NMSG_VENDOR_ISC_ID		1
#define NMSG_VENDOR_ISC_NAME		"ISC"
#define NMSG_VENDOR_ISC			{ NMSG_VENDOR_ISC_ID, NMSG_VENDOR_ISC_NAME }

#define NMSG_VENDOR_SIE_ID		2
#define NMSG_VENDOR_SIE_NAME		"SIE"
#define NMSG_VENDOR_SIE			{ NMSG_VENDOR_SIE_ID, NMSG_VENDOR_SIE_NAME }

#define NMSG_VENDOR_GTISC_ID		3
#define NMSG_VENDOR_GTISC_NAME		"GTISC"
#define NMSG_VENDOR_GTISC		{ NMSG_VENDOR_GTISC_ID, NMSG_VENDOR_GTISC_NAME }

#define NMSG_VENDOR_DEFINTEL_ID		4
#define NMSG_VENDOR_DEFINTEL_NAME	"Defintel"
#define NMSG_VENDOR_DEFINTEL		{ NMSG_VENDOR_DEFINTEL_ID, NMSG_VENDOR_DEFINTEL_NAME }

#define NMSG_VENDOR_UNIVIE_ID		5
#define NMSG_VENDOR_UNIVIE_NAME		"Univie"
#define NMSG_VENDOR_UNIVIE		{ NMSG_VENDOR_UNIVIE_ID, NMSG_VENDOR_UNIVIE_NAME }

#define NMSG_VENDOR_UNVEILLANCE_ID	6
#define NMSG_VENDOR_UNVEILLANCE_NAME	"Unveillance"
#define NMSG_VENDOR_UNVEILLANCE		{ NMSG_VENDOR_UNVEILLANCE_ID, NMSG_VENDOR_UNVEILLANCE_NAME }

#define NMSG_VENDOR_WISC_ID		7
#define NMSG_VENDOR_WISC_NAME		"WISC"
#define NMSG_VENDOR_WISC		{ NMSG_VENDOR_WISC_ID, NMSG_VENDOR_WISC_NAME }

#endif /* NMSG_VENDORS_H */
