#ifndef NMSG_ISC_DEFS_H
#define NMSG_ISC_DEFS_H

#define NMSG_VENDOR_ISC_NCAP_ID		1
#define NMSG_VENDOR_ISC_NCAP_NAME	"ncap"

#define NMSG_VENDOR_ISC_EMAIL_ID	2
#define NMSG_VENDOR_ISC_EMAIL_NAME	"email"

#define NMSG_VENDOR_ISC_LINKPAIR_ID	3
#define NMSG_VENDOR_ISC_LINKPAIR_NAME	"linkpair"

#define NMSG_VENDOR_ISC_HTTP_ID		4
#define NMSG_VENDOR_ISC_HTTP_NAME	"http"

#define NMSG_VENDOR_ISC_IPCONN_ID	5
#define NMSG_VENDOR_ISC_IPCONN_NAME	"ipconn"

#define NMSG_VENDOR_ISC_LOGLINE_ID	6
#define NMSG_VENDOR_ISC_LOGLINE_NAME	"logline"

#define NMSG_VENDOR_ISC_DNS_ID		7
#define NMSG_VENDOR_ISC_DNS_NAME	"dns"

#endif /* NMSG_ISC_DEFS_H */
