/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "dns.pb-c.h"
void   nmsg__isc__dns__init
                     (Nmsg__Isc__Dns         *message)
{
  static Nmsg__Isc__Dns init_value = NMSG__ISC__DNS__INIT;
  *message = init_value;
}
size_t nmsg__isc__dns__get_packed_size
                     (const Nmsg__Isc__Dns *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__dns__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nmsg__isc__dns__pack
                     (const Nmsg__Isc__Dns *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__dns__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nmsg__isc__dns__pack_to_buffer
                     (const Nmsg__Isc__Dns *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__dns__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nmsg__Isc__Dns *
       nmsg__isc__dns__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nmsg__Isc__Dns *)
     protobuf_c_message_unpack (&nmsg__isc__dns__descriptor,
                                allocator, len, data);
}
void   nmsg__isc__dns__free_unpacked
                     (Nmsg__Isc__Dns *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__dns__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nmsg__isc__dns__field_descriptors[5] =
{
  {
    "rrname",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Dns, has_rrname),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Dns, rrname),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "rrtype",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Dns, has_rrtype),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Dns, rrtype),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "rrclass",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Dns, has_rrclass),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Dns, rrclass),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "rrttl",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Dns, has_rrttl),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Dns, rrttl),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "rdata",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Dns, n_rdata),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Dns, rdata),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned nmsg__isc__dns__field_indices_by_name[] = {
  4,   /* field[4] = rdata */
  2,   /* field[2] = rrclass */
  0,   /* field[0] = rrname */
  3,   /* field[3] = rrttl */
  1,   /* field[1] = rrtype */
};
static const ProtobufCIntRange nmsg__isc__dns__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor nmsg__isc__dns__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nmsg.isc.Dns",
  "Dns",
  "Nmsg__Isc__Dns",
  "nmsg.isc",
  sizeof(Nmsg__Isc__Dns),
  5,
  nmsg__isc__dns__field_descriptors,
  nmsg__isc__dns__field_indices_by_name,
  1,  nmsg__isc__dns__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
