/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "emailhdr.pb-c.h"
size_t nmsg__isc__emailhdr__get_packed_size
                     (const Nmsg__Isc__Emailhdr *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__emailhdr__descriptor);
  return protobuf_c_message_get_packed_size ((ProtobufCMessage*)(message));
}
size_t nmsg__isc__emailhdr__pack
                     (const Nmsg__Isc__Emailhdr *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__emailhdr__descriptor);
  return protobuf_c_message_pack ((ProtobufCMessage*)message, out);
}
size_t nmsg__isc__emailhdr__pack_to_buffer
                     (const Nmsg__Isc__Emailhdr *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__emailhdr__descriptor);
  return protobuf_c_message_pack_to_buffer ((ProtobufCMessage*)message, buffer);
}
Nmsg__Isc__Emailhdr *
       nmsg__isc__emailhdr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nmsg__Isc__Emailhdr *)
     protobuf_c_message_unpack (&nmsg__isc__emailhdr__descriptor,
                                allocator, len, data);
}
void   nmsg__isc__emailhdr__free_unpacked
                     (Nmsg__Isc__Emailhdr *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__emailhdr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nmsg__isc__emailhdr__field_descriptors[10] =
{
  {
    "truncated",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_truncated),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, truncated),
    NULL
  },
  {
    "headers",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_headers),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, headers),
    NULL
  },
  {
    "srcip",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_srcip),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, srcip),
    NULL
  },
  {
    "srchost",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_srchost),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, srchost),
    NULL
  },
  {
    "helo",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_helo),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, helo),
    NULL
  },
  {
    "from",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_from),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, from),
    NULL
  },
  {
    "rcpt",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, n_rcpt),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, rcpt),
    NULL
  },
  {
    "bodylen",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_bodylen),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, bodylen),
    NULL
  },
  {
    "bodymd5",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_bodymd5),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, bodymd5),
    NULL
  },
  {
    "bodysha1",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_bodysha1),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, bodysha1),
    NULL
  },
};
static const unsigned nmsg__isc__emailhdr__field_indices_by_name[] = {
  7,   /* field[7] = bodylen */
  8,   /* field[8] = bodymd5 */
  9,   /* field[9] = bodysha1 */
  5,   /* field[5] = from */
  1,   /* field[1] = headers */
  4,   /* field[4] = helo */
  6,   /* field[6] = rcpt */
  3,   /* field[3] = srchost */
  2,   /* field[2] = srcip */
  0,   /* field[0] = truncated */
};
static const ProtobufCIntRange nmsg__isc__emailhdr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor nmsg__isc__emailhdr__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nmsg.isc.Emailhdr",
  "Emailhdr",
  "Nmsg__Isc__Emailhdr",
  "nmsg.isc",
  sizeof(Nmsg__Isc__Emailhdr),
  10,
  nmsg__isc__emailhdr__field_descriptors,
  nmsg__isc__emailhdr__field_indices_by_name,
  1,  nmsg__isc__emailhdr__number_ranges
};
