/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "emailhdr.pb-c.h"
void   nmsg__isc__emailhdr__init
                     (Nmsg__Isc__Emailhdr         *message)
{
  static Nmsg__Isc__Emailhdr init_value = NMSG__ISC__EMAILHDR__INIT;
  *message = init_value;
}
size_t nmsg__isc__emailhdr__get_packed_size
                     (const Nmsg__Isc__Emailhdr *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__emailhdr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nmsg__isc__emailhdr__pack
                     (const Nmsg__Isc__Emailhdr *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__emailhdr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nmsg__isc__emailhdr__pack_to_buffer
                     (const Nmsg__Isc__Emailhdr *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__emailhdr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nmsg__Isc__Emailhdr *
       nmsg__isc__emailhdr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nmsg__Isc__Emailhdr *)
     protobuf_c_message_unpack (&nmsg__isc__emailhdr__descriptor,
                                allocator, len, data);
}
void   nmsg__isc__emailhdr__free_unpacked
                     (Nmsg__Isc__Emailhdr *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__emailhdr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nmsg__isc__emailhdr__field_descriptors[7] =
{
  {
    "truncated",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_truncated),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, truncated),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "headers",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_headers),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, headers),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "srcip",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_srcip),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, srcip),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "srchost",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_srchost),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, srchost),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "helo",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_helo),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, helo),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "from",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, has_from),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, from),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "rcpt",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, n_rcpt),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Emailhdr, rcpt),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned nmsg__isc__emailhdr__field_indices_by_name[] = {
  5,   /* field[5] = from */
  1,   /* field[1] = headers */
  4,   /* field[4] = helo */
  6,   /* field[6] = rcpt */
  3,   /* field[3] = srchost */
  2,   /* field[2] = srcip */
  0,   /* field[0] = truncated */
};
static const ProtobufCIntRange nmsg__isc__emailhdr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor nmsg__isc__emailhdr__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nmsg.isc.Emailhdr",
  "Emailhdr",
  "Nmsg__Isc__Emailhdr",
  "nmsg.isc",
  sizeof(Nmsg__Isc__Emailhdr),
  7,
  nmsg__isc__emailhdr__field_descriptors,
  nmsg__isc__emailhdr__field_indices_by_name,
  1,  nmsg__isc__emailhdr__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
