/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "ipconn.pb-c.h"
void   nmsg__isc__ipconn__init
                     (Nmsg__Isc__IPConn         *message)
{
  static Nmsg__Isc__IPConn init_value = NMSG__ISC__IPCONN__INIT;
  *message = init_value;
}
size_t nmsg__isc__ipconn__get_packed_size
                     (const Nmsg__Isc__IPConn *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__ipconn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nmsg__isc__ipconn__pack
                     (const Nmsg__Isc__IPConn *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__ipconn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nmsg__isc__ipconn__pack_to_buffer
                     (const Nmsg__Isc__IPConn *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__ipconn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nmsg__Isc__IPConn *
       nmsg__isc__ipconn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nmsg__Isc__IPConn *)
     protobuf_c_message_unpack (&nmsg__isc__ipconn__descriptor,
                                allocator, len, data);
}
void   nmsg__isc__ipconn__free_unpacked
                     (Nmsg__Isc__IPConn *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__ipconn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nmsg__isc__ipconn__field_descriptors[5] =
{
  {
    "proto",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__IPConn, has_proto),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__IPConn, proto),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "srcip",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__IPConn, has_srcip),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__IPConn, srcip),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "srcport",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__IPConn, has_srcport),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__IPConn, srcport),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "dstip",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__IPConn, has_dstip),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__IPConn, dstip),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "dstport",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__IPConn, has_dstport),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__IPConn, dstport),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned nmsg__isc__ipconn__field_indices_by_name[] = {
  3,   /* field[3] = dstip */
  4,   /* field[4] = dstport */
  0,   /* field[0] = proto */
  1,   /* field[1] = srcip */
  2,   /* field[2] = srcport */
};
static const ProtobufCIntRange nmsg__isc__ipconn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor nmsg__isc__ipconn__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nmsg.isc.IPConn",
  "IPConn",
  "Nmsg__Isc__IPConn",
  "nmsg.isc",
  sizeof(Nmsg__Isc__IPConn),
  5,
  nmsg__isc__ipconn__field_descriptors,
  nmsg__isc__ipconn__field_indices_by_name,
  1,  nmsg__isc__ipconn__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
