/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "linkpair.pb-c.h"
void   nmsg__isc__linkpair__init
                     (Nmsg__Isc__Linkpair         *message)
{
  static Nmsg__Isc__Linkpair init_value = NMSG__ISC__LINKPAIR__INIT;
  *message = init_value;
}
size_t nmsg__isc__linkpair__get_packed_size
                     (const Nmsg__Isc__Linkpair *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__linkpair__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nmsg__isc__linkpair__pack
                     (const Nmsg__Isc__Linkpair *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__linkpair__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nmsg__isc__linkpair__pack_to_buffer
                     (const Nmsg__Isc__Linkpair *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__linkpair__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nmsg__Isc__Linkpair *
       nmsg__isc__linkpair__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nmsg__Isc__Linkpair *)
     protobuf_c_message_unpack (&nmsg__isc__linkpair__descriptor,
                                allocator, len, data);
}
void   nmsg__isc__linkpair__free_unpacked
                     (Nmsg__Isc__Linkpair *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__linkpair__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nmsg__isc__linkpair__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Linkpair, type),
    &nmsg__isc__linktype__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "src",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Linkpair, src),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "dst",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Linkpair, dst),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "truncated",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Linkpair, truncated),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "headers",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Linkpair, has_headers),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Linkpair, headers),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned nmsg__isc__linkpair__field_indices_by_name[] = {
  2,   /* field[2] = dst */
  4,   /* field[4] = headers */
  1,   /* field[1] = src */
  3,   /* field[3] = truncated */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange nmsg__isc__linkpair__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor nmsg__isc__linkpair__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nmsg.isc.Linkpair",
  "Linkpair",
  "Nmsg__Isc__Linkpair",
  "nmsg.isc",
  sizeof(Nmsg__Isc__Linkpair),
  5,
  nmsg__isc__linkpair__field_descriptors,
  nmsg__isc__linkpair__field_indices_by_name,
  1,  nmsg__isc__linkpair__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
const ProtobufCEnumValue nmsg__isc__linktype__enum_values_by_number[2] =
{
  { "anchor", "NMSG__ISC__LINKTYPE__ANCHOR", 0 },
  { "redirect", "NMSG__ISC__LINKTYPE__REDIRECT", 1 },
};
static const ProtobufCIntRange nmsg__isc__linktype__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex nmsg__isc__linktype__enum_values_by_name[2] =
{
  { "anchor", 0 },
  { "redirect", 1 },
};
const ProtobufCEnumDescriptor nmsg__isc__linktype__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "nmsg.isc.Linktype",
  "Linktype",
  "Nmsg__Isc__Linktype",
  "nmsg.isc",
  2,
  nmsg__isc__linktype__enum_values_by_number,
  2,
  nmsg__isc__linktype__enum_values_by_name,
  1,
  nmsg__isc__linktype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
