/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "logline.pb-c.h"
void   nmsg__isc__log_line__init
                     (Nmsg__Isc__LogLine         *message)
{
  static Nmsg__Isc__LogLine init_value = NMSG__ISC__LOG_LINE__INIT;
  *message = init_value;
}
size_t nmsg__isc__log_line__get_packed_size
                     (const Nmsg__Isc__LogLine *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__log_line__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nmsg__isc__log_line__pack
                     (const Nmsg__Isc__LogLine *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__log_line__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nmsg__isc__log_line__pack_to_buffer
                     (const Nmsg__Isc__LogLine *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__log_line__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nmsg__Isc__LogLine *
       nmsg__isc__log_line__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nmsg__Isc__LogLine *)
     protobuf_c_message_unpack (&nmsg__isc__log_line__descriptor,
                                allocator, len, data);
}
void   nmsg__isc__log_line__free_unpacked
                     (Nmsg__Isc__LogLine *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__log_line__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nmsg__isc__log_line__field_descriptors[2] =
{
  {
    "category",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__LogLine, has_category),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__LogLine, category),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__LogLine, has_message),
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__LogLine, message),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned nmsg__isc__log_line__field_indices_by_name[] = {
  0,   /* field[0] = category */
  1,   /* field[1] = message */
};
static const ProtobufCIntRange nmsg__isc__log_line__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nmsg__isc__log_line__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nmsg.isc.LogLine",
  "LogLine",
  "Nmsg__Isc__LogLine",
  "nmsg.isc",
  sizeof(Nmsg__Isc__LogLine),
  2,
  nmsg__isc__log_line__field_descriptors,
  nmsg__isc__log_line__field_indices_by_name,
  1,  nmsg__isc__log_line__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
