/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "ncap.pb-c.h"
void   nmsg__isc__ncap__init
                     (Nmsg__Isc__Ncap         *message)
{
  static Nmsg__Isc__Ncap init_value = NMSG__ISC__NCAP__INIT;
  *message = init_value;
}
size_t nmsg__isc__ncap__get_packed_size
                     (const Nmsg__Isc__Ncap *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__ncap__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nmsg__isc__ncap__pack
                     (const Nmsg__Isc__Ncap *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__ncap__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nmsg__isc__ncap__pack_to_buffer
                     (const Nmsg__Isc__Ncap *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__ncap__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nmsg__Isc__Ncap *
       nmsg__isc__ncap__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nmsg__Isc__Ncap *)
     protobuf_c_message_unpack (&nmsg__isc__ncap__descriptor,
                                allocator, len, data);
}
void   nmsg__isc__ncap__free_unpacked
                     (Nmsg__Isc__Ncap *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nmsg__isc__ncap__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nmsg__isc__ncap__field_descriptors[2] =
{
  {
    "ether_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Ncap, ether_type),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "payload",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nmsg__Isc__Ncap, payload),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned nmsg__isc__ncap__field_indices_by_name[] = {
  0,   /* field[0] = ether_type */
  1,   /* field[1] = payload */
};
static const ProtobufCIntRange nmsg__isc__ncap__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nmsg__isc__ncap__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "nmsg.isc.Ncap",
  "Ncap",
  "Nmsg__Isc__Ncap",
  "nmsg.isc",
  sizeof(Nmsg__Isc__Ncap),
  2,
  nmsg__isc__ncap__field_descriptors,
  nmsg__isc__ncap__field_indices_by_name,
  1,  nmsg__isc__ncap__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
