/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_ncap_2eproto__INCLUDED
#define PROTOBUF_C_ncap_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Nmsg__Isc__Ncap Nmsg__Isc__Ncap;


/* --- enums --- */

typedef enum _Nmsg__Isc__NcapType {
  NMSG__ISC__NCAP_TYPE__IPV4 = 0,
  NMSG__ISC__NCAP_TYPE__IPV6 = 1,
  NMSG__ISC__NCAP_TYPE__Legacy = 2
} Nmsg__Isc__NcapType;
typedef enum _Nmsg__Isc__NcapLegacyType {
  NMSG__ISC__NCAP_LEGACY_TYPE__UDP = 0,
  NMSG__ISC__NCAP_LEGACY_TYPE__TCP = 1,
  NMSG__ISC__NCAP_LEGACY_TYPE__ICMP = 2
} Nmsg__Isc__NcapLegacyType;

/* --- messages --- */

struct  _Nmsg__Isc__Ncap
{
  ProtobufCMessage base;
  Nmsg__Isc__NcapType type;
  ProtobufCBinaryData payload;
  protobuf_c_boolean has_ltype;
  Nmsg__Isc__NcapLegacyType ltype;
  protobuf_c_boolean has_srcip;
  ProtobufCBinaryData srcip;
  protobuf_c_boolean has_dstip;
  ProtobufCBinaryData dstip;
  protobuf_c_boolean has_lint0;
  uint32_t lint0;
  protobuf_c_boolean has_lint1;
  uint32_t lint1;
};
#define NMSG__ISC__NCAP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nmsg__isc__ncap__descriptor) \
    , 0, {0,NULL}, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,0 }


/* Nmsg__Isc__Ncap methods */
void   nmsg__isc__ncap__init
                     (Nmsg__Isc__Ncap         *message);
size_t nmsg__isc__ncap__get_packed_size
                     (const Nmsg__Isc__Ncap   *message);
size_t nmsg__isc__ncap__pack
                     (const Nmsg__Isc__Ncap   *message,
                      uint8_t             *out);
size_t nmsg__isc__ncap__pack_to_buffer
                     (const Nmsg__Isc__Ncap   *message,
                      ProtobufCBuffer     *buffer);
Nmsg__Isc__Ncap *
       nmsg__isc__ncap__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nmsg__isc__ncap__free_unpacked
                     (Nmsg__Isc__Ncap *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Nmsg__Isc__Ncap_Closure)
                 (const Nmsg__Isc__Ncap *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    nmsg__isc__ncap_type__descriptor;
extern const ProtobufCEnumDescriptor    nmsg__isc__ncap_legacy_type__descriptor;
extern const ProtobufCMessageDescriptor nmsg__isc__ncap__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_ncap_2eproto__INCLUDED */
